# Jekyll configuration

name: The Audacity of Thought
description: (Yup, i lifted the blog name idea from Obama) Trying to make sense of this world and our existence in it, this blog is to document knowledge, my writings, and opinions, on a variety of things i like to read and write about. Most posts shall have a probing theme since this is a channel for my contemplation on a lot of things. Take a look at the categories and see if we resonate on something.

# Url is currently only used only for the RSS feed in feed.xml
url: http://ninad-dholakia.github.io
#url: http://localhost:4000

# For a project page here should be a project name. Otherwise (for user's/organization's page leave it empty)
baseurl: ''

author: Ninad Dholakia
copyright: 2023

share:
  facebook: true
  twitter: true
  gplus: true
  linkedin: true
  pinterest: true
  email: true

social:
  github: ninad-dholakia
  twitter: ssly_funny
  stackoverflow: ''
  linkedin: ''
  instagram: ''
  lastfm: ''
  rss: feed.xml

# Google Analytics key, leave blank to ignore
google_analytics_key:
# Yandex metrica (https://metrica.yandex.com/) leave blank to ignore or put true to use
yandex_metrica:


# Set this to your disqus shortname to enable comments. Note that the 'comments'
# setting below must also be true. Individual posts can override 'comments' to
# disable on a post-by-post basis
disqus: streetturtle
comments: false

permalink: /:year/:month/:title/

# Enable for using pages, more details are here: http://jekyllrb.com/docs/pagination/
#paginate: 3

#highlighter: rouge

markdown: kramdown
kramdown:
  input: GFM # Enable GitHub Flavored Markdown (fenced code blocks)
  hard_wrap: true

exclude: ['README.md', 'LICENSE']
